5 REM ARRAYS
10 DIM A(5) : REM CREATING A 1D ARRAY OF 15 ELEMENTS, THE ARRAY'S NAME IS A. INDICES START FROM 0 AND GO TILL 5(NOT 4). SO, ACTUALLY WE HAVE ALLOWED 6 NUMBERS IN THE ARRAY.

20 PRINT "ENTER ELEMENTS INTO THE ARRAY: "
30 FOR I=0 TO 5
40 PRINT "ELEMENT ", I
50 INPUT A(I)
60 NEXT I
65 HOME
70 PRINT "ELEMENTS IN THE ARRAY ARE: "
80 FOR I=0 TO 5
90 PRINT A(I)
100 NEXT I
